# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class airchief < Formula
  desc "The AI coding agent built for the terminal."
  homepage "https://github.com/shaneholloman/airchief"
  version "0.1.115"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shaneholloman/airchief/releases/download/v0.3.0/airchief-darwin-x64.zip"
      sha256 "4b7dcfb3b41a9a072e46643692bc18c3b0c5677e0b419124ccef5f8e5d54768d"

      def install
        bin.install "airchief"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shaneholloman/airchief/releases/download/v0.3.0/airchief-darwin-arm64.zip"
      sha256 "d89fa2f760aa087584d91fe32a94cb11209985aca503c373283606e5e127582a"

      def install
        bin.install "airchief"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/shaneholloman/airchief/releases/download/v0.3.0/airchief-linux-x64.zip"
      sha256 "9db1c73e4daab7abfece44f5b9db02307669052c83d83222b0bc4add7656ec3d"
      def install
        bin.install "airchief"
      end
    end
  end
end
